# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createNew.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateNew(object):
    def setupUi(self, CreateNew):
        CreateNew.setObjectName("CreateNew")
        CreateNew.resize(819, 243)
        CreateNew.setWindowOpacity(1.0)
        CreateNew.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(CreateNew)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_page = QtWidgets.QGroupBox(CreateNew)
        self.group_page.setObjectName("group_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.group_page)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbPageSize = QtWidgets.QComboBox(self.group_page)
        self.cmbPageSize.setObjectName("cmbPageSize")
        self.cmbPageSize.addItem("")
        self.cmbPageSize.addItem("")
        self.cmbPageSize.addItem("")
        self.horizontalLayout.addWidget(self.cmbPageSize)
        self.label_2 = QtWidgets.QLabel(self.group_page)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spbLeftPadding = QtWidgets.QSpinBox(self.group_page)
        self.spbLeftPadding.setProperty("value", 20)
        self.spbLeftPadding.setObjectName("spbLeftPadding")
        self.horizontalLayout.addWidget(self.spbLeftPadding)
        self.label_3 = QtWidgets.QLabel(self.group_page)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.group_page)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spbTopPadding = QtWidgets.QSpinBox(self.group_page)
        self.spbTopPadding.setProperty("value", 20)
        self.spbTopPadding.setObjectName("spbTopPadding")
        self.horizontalLayout.addWidget(self.spbTopPadding)
        self.label_5 = QtWidgets.QLabel(self.group_page)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.group_page)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.spbRightPadding = QtWidgets.QSpinBox(self.group_page)
        self.spbRightPadding.setProperty("value", 20)
        self.spbRightPadding.setObjectName("spbRightPadding")
        self.horizontalLayout.addWidget(self.spbRightPadding)
        self.label_8 = QtWidgets.QLabel(self.group_page)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.group_page)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spbBottomPadding = QtWidgets.QSpinBox(self.group_page)
        self.spbBottomPadding.setProperty("value", 20)
        self.spbBottomPadding.setObjectName("spbBottomPadding")
        self.horizontalLayout.addWidget(self.spbBottomPadding)
        self.label_6 = QtWidgets.QLabel(self.group_page)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout_3.addWidget(self.group_page)
        self.group_label = QtWidgets.QGroupBox(CreateNew)
        self.group_label.setObjectName("group_label")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_label)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.group_label)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.startUnit = QtWidgets.QComboBox(self.group_label)
        self.startUnit.setObjectName("startUnit")
        self.startUnit.addItem("")
        self.horizontalLayout_2.addWidget(self.startUnit)
        self.label_11 = QtWidgets.QLabel(self.group_label)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.endUnit = QtWidgets.QComboBox(self.group_label)
        self.endUnit.setObjectName("endUnit")
        self.endUnit.addItem("")
        self.horizontalLayout_2.addWidget(self.endUnit)
        self.label_12 = QtWidgets.QLabel(self.group_label)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.spbColumns = QtWidgets.QSpinBox(self.group_label)
        self.spbColumns.setMinimum(1)
        self.spbColumns.setMaximum(5)
        self.spbColumns.setProperty("value", 2)
        self.spbColumns.setObjectName("spbColumns")
        self.horizontalLayout_2.addWidget(self.spbColumns)
        self.label_16 = QtWidgets.QLabel(self.group_label)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.spbColMargin = QtWidgets.QSpinBox(self.group_label)
        self.spbColMargin.setProperty("value", 5)
        self.spbColMargin.setObjectName("spbColMargin")
        self.horizontalLayout_2.addWidget(self.spbColMargin)
        self.label_15 = QtWidgets.QLabel(self.group_label)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.printPageNumber = QtWidgets.QCheckBox(self.group_label)
        self.printPageNumber.setChecked(True)
        self.printPageNumber.setObjectName("printPageNumber")
        self.horizontalLayout_2.addWidget(self.printPageNumber)
        self.isRandom = QtWidgets.QCheckBox(self.group_label)
        self.isRandom.setChecked(True)
        self.isRandom.setObjectName("isRandom")
        self.horizontalLayout_2.addWidget(self.isRandom)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.group_label)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.selectWords = QtWidgets.QCheckBox(self.group_label)
        self.selectWords.setChecked(True)
        self.selectWords.setObjectName("selectWords")
        self.horizontalLayout_3.addWidget(self.selectWords)
        self.selectWordGroup = QtWidgets.QCheckBox(self.group_label)
        self.selectWordGroup.setChecked(True)
        self.selectWordGroup.setObjectName("selectWordGroup")
        self.horizontalLayout_3.addWidget(self.selectWordGroup)
        self.printCh = QtWidgets.QRadioButton(self.group_label)
        self.printCh.setObjectName("printCh")
        self.horizontalLayout_3.addWidget(self.printCh)
        self.printEn = QtWidgets.QRadioButton(self.group_label)
        self.printEn.setChecked(True)
        self.printEn.setObjectName("printEn")
        self.horizontalLayout_3.addWidget(self.printEn)
        self.createAnswer = QtWidgets.QCheckBox(self.group_label)
        self.createAnswer.setChecked(True)
        self.createAnswer.setObjectName("createAnswer")
        self.horizontalLayout_3.addWidget(self.createAnswer)
        self.label_19 = QtWidgets.QLabel(self.group_label)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.lineHeight = QtWidgets.QSpinBox(self.group_label)
        self.lineHeight.setMinimum(1)
        self.lineHeight.setProperty("value", 10)
        self.lineHeight.setObjectName("lineHeight")
        self.horizontalLayout_3.addWidget(self.lineHeight)
        self.label_18 = QtWidgets.QLabel(self.group_label)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.d_page = QtWidgets.QCheckBox(self.group_label)
        self.d_page.setObjectName("d_page")
        self.horizontalLayout_3.addWidget(self.d_page)
        self.onlyError = QtWidgets.QCheckBox(self.group_label)
        self.onlyError.setObjectName("onlyError")
        self.horizontalLayout_3.addWidget(self.onlyError)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.group_label)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnCreate = QtWidgets.QPushButton(CreateNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreate.sizePolicy().hasHeightForWidth())
        self.btnCreate.setSizePolicy(sizePolicy)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout_4.addWidget(self.btnCreate)
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnOpenPDF = QtWidgets.QPushButton(CreateNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenPDF.sizePolicy().hasHeightForWidth())
        self.btnOpenPDF.setSizePolicy(sizePolicy)
        self.btnOpenPDF.setObjectName("btnOpenPDF")
        self.horizontalLayout_4.addWidget(self.btnOpenPDF)
        spacerItem2 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnClose = QtWidgets.QPushButton(CreateNew)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_4.addWidget(self.btnClose)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.label.setBuddy(self.cmbPageSize)
        self.label_2.setBuddy(self.spbLeftPadding)
        self.label_3.setBuddy(self.spbLeftPadding)
        self.label_4.setBuddy(self.spbTopPadding)
        self.label_5.setBuddy(self.spbTopPadding)
        self.label_9.setBuddy(self.spbRightPadding)
        self.label_8.setBuddy(self.spbRightPadding)
        self.label_7.setBuddy(self.spbBottomPadding)
        self.label_6.setBuddy(self.spbBottomPadding)
        self.label_10.setBuddy(self.startUnit)
        self.label_11.setBuddy(self.endUnit)
        self.label_12.setBuddy(self.spbColumns)
        self.label_16.setBuddy(self.spbColMargin)
        self.label_19.setBuddy(self.lineHeight)
        self.label_18.setBuddy(self.lineHeight)

        self.retranslateUi(CreateNew)
        self.btnClose.clicked.connect(CreateNew.close)
        QtCore.QMetaObject.connectSlotsByName(CreateNew)

    def retranslateUi(self, CreateNew):
        _translate = QtCore.QCoreApplication.translate
        CreateNew.setWindowTitle(_translate("CreateNew", "生成新练习"))
        self.group_page.setTitle(_translate("CreateNew", "页面设置"))
        self.label.setText(_translate("CreateNew", "纸型："))
        self.cmbPageSize.setItemText(0, _translate("CreateNew", "A4"))
        self.cmbPageSize.setItemText(1, _translate("CreateNew", "B5"))
        self.cmbPageSize.setItemText(2, _translate("CreateNew", "A3"))
        self.label_2.setText(_translate("CreateNew", "左边距："))
        self.label_3.setText(_translate("CreateNew", "毫米"))
        self.label_4.setText(_translate("CreateNew", "顶边距："))
        self.label_5.setText(_translate("CreateNew", "毫米"))
        self.label_9.setText(_translate("CreateNew", "右边距："))
        self.label_8.setText(_translate("CreateNew", "毫米"))
        self.label_7.setText(_translate("CreateNew", "底边距："))
        self.label_6.setText(_translate("CreateNew", "毫米"))
        self.group_label.setTitle(_translate("CreateNew", "内容设置"))
        self.label_10.setText(_translate("CreateNew", "起始单元："))
        self.startUnit.setItemText(0, _translate("CreateNew", "1.1"))
        self.label_11.setText(_translate("CreateNew", "结束单元："))
        self.endUnit.setItemText(0, _translate("CreateNew", "1.1"))
        self.label_12.setText(_translate("CreateNew", "列数："))
        self.label_16.setText(_translate("CreateNew", "列间距："))
        self.label_15.setText(_translate("CreateNew", "毫米"))
        self.printPageNumber.setText(_translate("CreateNew", "打印页码"))
        self.isRandom.setText(_translate("CreateNew", "乱序打印"))
        self.label_17.setText(_translate("CreateNew", "打印内容："))
        self.selectWords.setText(_translate("CreateNew", "单词"))
        self.selectWordGroup.setText(_translate("CreateNew", "词组"))
        self.printCh.setText(_translate("CreateNew", "打印中文"))
        self.printEn.setText(_translate("CreateNew", "打印英文"))
        self.createAnswer.setText(_translate("CreateNew", "生成答案"))
        self.label_19.setText(_translate("CreateNew", "行高："))
        self.label_18.setText(_translate("CreateNew", "毫米"))
        self.d_page.setText(_translate("CreateNew", "双面"))
        self.onlyError.setText(_translate("CreateNew", "只选错词"))
        self.btnCreate.setText(_translate("CreateNew", "生成PDF"))
        self.btnOpenPDF.setText(_translate("CreateNew", "打开PDF"))
        self.btnClose.setText(_translate("CreateNew", "关闭"))

