# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dispAll = QtWidgets.QCheckBox(self.layoutWidget)
        self.dispAll.setObjectName("dispAll")
        self.horizontalLayout.addWidget(self.dispAll, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listTesting = QtWidgets.QListWidget(self.layoutWidget)
        self.listTesting.setMinimumSize(QtCore.QSize(150, 0))
        self.listTesting.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listTesting.setObjectName("listTesting")
        self.verticalLayout.addWidget(self.listTesting)
        self.btnNew = QtWidgets.QPushButton(self.layoutWidget)
        self.btnNew.setMinimumSize(QtCore.QSize(75, 0))
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout.addWidget(self.btnNew)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupTestingInfo = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupTestingInfo.sizePolicy().hasHeightForWidth())
        self.groupTestingInfo.setSizePolicy(sizePolicy)
        self.groupTestingInfo.setMinimumSize(QtCore.QSize(580, 120))
        self.groupTestingInfo.setObjectName("groupTestingInfo")
        self.btnCreate = QtWidgets.QPushButton(self.groupTestingInfo)
        self.btnCreate.setGeometry(QtCore.QRect(10, 90, 91, 23))
        self.btnCreate.setMinimumSize(QtCore.QSize(75, 0))
        self.btnCreate.setObjectName("btnCreate")
        self.label_2 = QtWidgets.QLabel(self.groupTestingInfo)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_2.setObjectName("label_2")
        self.t_name = QtWidgets.QLabel(self.groupTestingInfo)
        self.t_name.setGeometry(QtCore.QRect(70, 30, 181, 16))
        self.t_name.setObjectName("t_name")
        self.label_3 = QtWidgets.QLabel(self.groupTestingInfo)
        self.label_3.setGeometry(QtCore.QRect(380, 30, 54, 16))
        self.label_3.setObjectName("label_3")
        self.t_type = QtWidgets.QLabel(self.groupTestingInfo)
        self.t_type.setGeometry(QtCore.QRect(440, 30, 111, 16))
        self.t_type.setObjectName("t_type")
        self.label_5 = QtWidgets.QLabel(self.groupTestingInfo)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 54, 16))
        self.label_5.setObjectName("label_5")
        self.t_content = QtWidgets.QLabel(self.groupTestingInfo)
        self.t_content.setGeometry(QtCore.QRect(70, 60, 161, 16))
        self.t_content.setObjectName("t_content")
        self.label_7 = QtWidgets.QLabel(self.groupTestingInfo)
        self.label_7.setGeometry(QtCore.QRect(190, 60, 54, 16))
        self.label_7.setObjectName("label_7")
        self.t_CreateTime = QtWidgets.QLabel(self.groupTestingInfo)
        self.t_CreateTime.setGeometry(QtCore.QRect(250, 60, 121, 16))
        self.t_CreateTime.setObjectName("t_CreateTime")
        self.label_9 = QtWidgets.QLabel(self.groupTestingInfo)
        self.label_9.setGeometry(QtCore.QRect(380, 60, 81, 16))
        self.label_9.setObjectName("label_9")
        self.t_LastModi = QtWidgets.QLabel(self.groupTestingInfo)
        self.t_LastModi.setGeometry(QtCore.QRect(470, 60, 121, 16))
        self.t_LastModi.setObjectName("t_LastModi")
        self.btnCorrect = QtWidgets.QPushButton(self.groupTestingInfo)
        self.btnCorrect.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.btnCorrect.setMinimumSize(QtCore.QSize(75, 0))
        self.btnCorrect.setObjectName("btnCorrect")
        self.btnCancelCorrect = QtWidgets.QPushButton(self.groupTestingInfo)
        self.btnCancelCorrect.setEnabled(False)
        self.btnCancelCorrect.setGeometry(QtCore.QRect(240, 90, 75, 23))
        self.btnCancelCorrect.setMinimumSize(QtCore.QSize(75, 0))
        self.btnCancelCorrect.setObjectName("btnCancelCorrect")
        self.btnDone = QtWidgets.QPushButton(self.groupTestingInfo)
        self.btnDone.setGeometry(QtCore.QRect(340, 90, 80, 23))
        self.btnDone.setObjectName("btnDone")
        self.verticalLayout_2.addWidget(self.groupTestingInfo)
        self.tabWords = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tabWords.setEnabled(True)
        self.tabWords.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabWords.setProperty("showDropIndicator", False)
        self.tabWords.setDragDropOverwriteMode(False)
        self.tabWords.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tabWords.setCornerButtonEnabled(False)
        self.tabWords.setRowCount(0)
        self.tabWords.setObjectName("tabWords")
        self.tabWords.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWords.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.tabWords)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.listTesting)

        self.retranslateUi(MainWindow)
        self.btnNew.clicked.connect(MainWindow.show)
        self.btnCorrect.clicked['bool'].connect(self.btnCancelCorrect.setDisabled)
        self.btnCancelCorrect.clicked['bool'].connect(self.btnCancelCorrect.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "练习浏览"))
        self.label.setText(_translate("MainWindow", "练习列表："))
        self.dispAll.setText(_translate("MainWindow", "显示全部"))
        self.btnNew.setText(_translate("MainWindow", "新建练习"))
        self.groupTestingInfo.setTitle(_translate("MainWindow", "练习信息"))
        self.btnCreate.setToolTip(_translate("MainWindow", "生成指定设置的PDF练习文件"))
        self.btnCreate.setText(_translate("MainWindow", "再次生成PDF"))
        self.label_2.setText(_translate("MainWindow", "练习名称："))
        self.t_name.setText(_translate("MainWindow", "第01册第01单元－第01册02单元"))
        self.label_3.setText(_translate("MainWindow", "练习类型："))
        self.t_type.setText(_translate("MainWindow", "单词和词组"))
        self.label_5.setText(_translate("MainWindow", "练习内容："))
        self.t_content.setText(_translate("MainWindow", "看中文写英文"))
        self.label_7.setText(_translate("MainWindow", "生成时间："))
        self.t_CreateTime.setText(_translate("MainWindow", "2018-10-01 15:59"))
        self.label_9.setText(_translate("MainWindow", "完成批改时间："))
        self.t_LastModi.setText(_translate("MainWindow", "2018-10-01 15:59"))
        self.btnCorrect.setToolTip(_translate("MainWindow", "进入批改状态"))
        self.btnCorrect.setText(_translate("MainWindow", "批改"))
        self.btnCancelCorrect.setToolTip(_translate("MainWindow", "取消本次批改"))
        self.btnCancelCorrect.setText(_translate("MainWindow", "取消"))
        self.btnDone.setText(_translate("MainWindow", "结束批改"))
        item = self.tabWords.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabWords.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型"))
        item = self.tabWords.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "英文"))
        item = self.tabWords.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "中文"))
        item = self.tabWords.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "对错"))
        item = self.tabWords.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "已错(次)"))
        item = self.tabWords.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "已练(次)"))
        item = self.tabWords.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "错误率(%)"))

